version: '3.4'

services:
  newmjscicd:
    image: gitasriadnyani/mjs-cicd
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
